//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyTicket
    {
        public int Id { get; set; }
        public int ShowTimeId { get; set; }
        public int ChairId { get; set; }
        public int BuyerId { get; set; }
        public System.DateTime DateShopping { get; set; }
        public byte TicketStatusId { get; set; }
        public string TrackingCode { get; set; }
        public int Price { get; set; }
    
        public virtual Buyer Buyer { get; set; }
        public virtual Chair Chair { get; set; }
        public virtual ShowTime ShowTime { get; set; }
        public virtual TicketStatu TicketStatu { get; set; }
    }
}
