//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chair
    {
        public Chair()
        {
            this.BuyTickets = new HashSet<BuyTicket>();
        }
    
        public int Id { get; set; }
        public int Row { get; set; }
        public int Column { get; set; }
        public int HallPartId { get; set; }
        public string Number { get; set; }
    
        public virtual ICollection<BuyTicket> BuyTickets { get; set; }
        public virtual HallPart HallPart { get; set; }
    }
}
