//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConcertPrice
    {
        public int Id { get; set; }
        public int ConcertId { get; set; }
        public decimal Prices { get; set; }
        public byte TheRow { get; set; }
        public byte ToRow { get; set; }
        public Nullable<int> HallPartId { get; set; }
    
        public virtual Concert Concert { get; set; }
        public virtual HallPart HallPart { get; set; }
    }
}
