//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConcertTicket
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public int TicketCount { get; set; }
        public Nullable<int> ticketSum { get; set; }
        public Nullable<int> Price { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string BankName { get; set; }
        public string TrackingCode { get; set; }
        public int ShowTimeId { get; set; }
        public int BuyerId { get; set; }
        public int Id { get; set; }
    }
}
