//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConcertShowTime
    {
        public string ConcertTitle { get; set; }
        public string HallName { get; set; }
        public string Subject { get; set; }
        public int ShowTimeId { get; set; }
        public int ConcertId { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
    }
}
