//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hall
    {
        public Hall()
        {
            this.Concerts = new HashSet<Concert>();
            this.HallParts = new HashSet<HallPart>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Length { get; set; }
        public string Width { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Langitude { get; set; }
    
        public virtual ICollection<Concert> Concerts { get; set; }
        public virtual ICollection<HallPart> HallParts { get; set; }
    }
}
