//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowTime
    {
        public ShowTime()
        {
            this.BuyTickets = new HashSet<BuyTicket>();
        }
    
        public int Id { get; set; }
        public string Subject { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime End { get; set; }
        public int ConcertId { get; set; }
        public bool IsCanceled { get; set; }
        public string RecurrenceRule { get; set; }
        public Nullable<int> RecurrenceParentId { get; set; }
    
        public virtual ICollection<BuyTicket> BuyTickets { get; set; }
        public virtual Concert Concert { get; set; }
    }
}
