//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Singer
    {
        public Singer()
        {
            this.Concerts = new HashSet<Concert>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Mobile { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public string ImageURL { get; set; }
    
        public virtual ICollection<Concert> Concerts { get; set; }
    }
}
